Don't use -debug-info-kind=constructor when xcode_clang is used.
At the moment -debug-info-kind=constructor is unsupported by xcode clang.

Error example:
error: invalid value 'constructor' in '-debug-info-kind=constructor'

https://ci.chromium.org/p/webrtc/builders/ci/iOS%20API%20Framework%20Builder/16174

Bug: 1050118
Change-Id: Iff98ca1d830e6280b3dcb38362fb8351e9336cd0
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2072238
Reviewed-by: Nico Weber <thakis@chromium.org>
Reviewed-by: Mirko Bonadei <mbonadei@chromium.org>
Commit-Queue: Nico Weber <thakis@chromium.org>
Auto-Submit: Courtney Edwards <courtneyfe@chromium.org>
Cr-Original-Commit-Position: refs/heads/master@{#744245}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: f28e8e90bb2d0a41d0d7552922c5b756dfc2e97a