Revert "Enable -Wunreachable-code on Windows."
This reverts commit e334b16ecf6802a00a35cf48fe3916c2a292d969.

Reason for revert: Breaks win-asan

https://ci.chromium.org/p/chromium/builders/ci/win-asan/11193

../../sandbox/win/src/process_mitigations_dyncode_unittest.cc(414,31): error: code will never be executed [-Werror,-Wunreachable-code]
std::wstring test_command = L"CheckPolicy ";
^~~~~~~~~~~~~~~
../../sandbox/win/src/process_mitigations_dyncode_unittest.cc(490,31): error: code will never be executed [-Werror,-Wunreachable-code]
std::wstring test_command = L"CheckPolicy ";
^~~~~~~~~~~~~~~


Original change's description:
> Enable -Wunreachable-code on Windows.
> 
> TBR=reillyg
> 
> Bug: 346399
> Change-Id: I7f52d34dd3be08485c1aace38f2f61d1d4f14176
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2122428
> Commit-Queue: Nico Weber <thakis@chromium.org>
> Auto-Submit: Nico Weber <thakis@chromium.org>
> Reviewed-by: Robert Sesek <rsesek@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#753741}

TBR=thakis@chromium.org,reillyg@chromium.org,rsesek@chromium.org

Change-Id: I289e69d3147aa774a5637fffa850f55015ea5d67
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 346399
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2122434
Reviewed-by: Avi Drissman <avi@chromium.org>
Commit-Queue: Avi Drissman <avi@chromium.org>
Cr-Original-Commit-Position: refs/heads/master@{#753767}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 6d6956573c0e1b0a9fde22feb2f51efdd70df8bb