siso: Fix missing inputs for remote linking in chromeos arm64 builds
The cros arm64 builders need aarch64 toolchains.

```
FileNotFoundError: [Errno 2] No such file or directory: '../../build/cros_cache/chrome-sdk/symlinks/arm64-generic+16077.0.0-1064334+target_toolchain/bin/aarch64-cros-linux-gnu-clang++'
```

Bug: 370860664
Change-Id: Id161b48922b055d09ee941ac0a417669bbd010e2
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5973360
Commit-Queue: Junji Watanabe <jwata@google.com>
Reviewed-by: Fumitoshi Ukai <ukai@google.com>
Cr-Commit-Position: refs/heads/main@{#1375038}
NOKEYCHECK=True
GitOrigin-RevId: 5ecec0a4e0f218c817f3926758959c1c531af6f7