Allow building with is_clang=false, use_sysroot=true
Building with the wheezy sysroot and is_clang=false results in errors
like this:

../../base/process/process_iterator.h:12:16: fatal error: list: No
such file or directory
 #include <list>

[1] added a restriction that use_sysroot must be false when building
with is_clang=false.  However, as of [2], the wheezy sysroot has been
removed, and these compilation errors are not present on the Jessie
sysroot.  This CL removes the restriction added by [1].

[1] https://codereview.chromium.org/1476923005
[2] https://codereview.chromium.org/2597523003

BUG=575778
R=dpranke@chromium.org

Review-Url: https://codereview.chromium.org/2804633005
Cr-Original-Commit-Position: refs/heads/master@{#462343}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: c2c8a4d94797d67f76e061be40cfed0378eccd81