Revert "Add swiftshader to MSan ignore list"
This reverts commit 1879d320d120991597e139238962d878d4791b4e.

Reason for revert: Broke MSan bots

`gn_hash_file.py` errors with:
```
AttributeError: module 'hashlib' has no attribute 'file_digest'
```

Probably bots have different library version?

Failed builds:

Builder: Libfuzzer Upload Linux MSan
https://ci.chromium.org/p/chromium/builders/ci/Libfuzzer%20Upload%20Linux%20MSan
First failing build:
https://ci.chromium.org/p/chromium/builders/ci/Libfuzzer%20Upload%20Linux%20MSan/b8749728837640929521
Step "generate_build_files" failing on builder "chromium/ci/Linux ChromiumOS MSan Builder"

Builder: Linux ChromiumOS MSan Builder
https://ci.chromium.org/p/chromium/builders/ci/Linux%20ChromiumOS%20MSan%20Builder
First failing build:
https://ci.chromium.org/p/chromium/builders/ci/Linux%20ChromiumOS%20MSan%20Builder/b8749732408071057681
Step "generate_build_files" failing on builder "chromium/ci/Linux MSan Builder

Builder: Linux MSan Builder
https://ci.chromium.org/p/chromium/builders/ci/Linux%20MSan%20Builder
First failing build:
https://ci.chromium.org/p/chromium/builders/ci/Linux%20MSan%20Builder/b8749732084627613697
Step "generate_build_files" failing on builder "chromium/ci/MSAN Release (chained origins)

Builder: MSAN Release (chained origins)
https://ci.chromium.org/p/chromium/builders/ci/MSAN%20Release%20%28chained%20origins%29
First failing build:
https://ci.chromium.org/p/chromium/builders/ci/MSAN%20Release%20%28chained%20origins%29/b8749732398598287617
Step "generate_build_files" failing on builder "chromium/ci/MSAN Release (no origins)"

Builder: MSAN Release (no origins)
https://ci.chromium.org/p/chromium/builders/ci/MSAN%20Release%20%28no%20origins%29
First failing build:
https://ci.chromium.org/p/chromium/builders/ci/MSAN%20Release%20%28no%20origins%29/b8749732527096818881
Step "generate_build_files" failing on builder "chromium/ci/WebKit Linux MSAN"

Builder: WebKit Linux MSAN
https://ci.chromium.org/p/chromium/builders/ci/WebKit%20Linux%20MSAN
First failing build:
https://ci.chromium.org/p/chromium/builders/ci/WebKit%20Linux%20MSAN/b8749728993493108897

Original change's description:
> Add swiftshader to MSan ignore list
>
> While it would certainly be preferable to MSan instrument Swiftshader,
> there does not appear to be a viable path to doing so in the short or
> medium term. Swiftshader is no longer actively maintained and is on the
> blocking path to enabling -fsanitize-memory-param-retval (and by
> extension, running Rust with MSan). This new MSan mode is stricter and
> disallows passing uninit values as parameters or return values—which is
> something that was previously only caught if the uninit parameter or
> return value ended up being used in a conditional branch.  ,
>
> Swiftshader itself is being removed as a default fallback for WebGL (see
> crbug.com/40277080) which should reduce the need to have this actively
> covered by MSan.
>
> Finally, also implement a more robust mechanism than a manual clobber
> for ensuring correct MSan builds when the ignorelist changes.
>
> Bug: 1369167
> Change-Id: Icae46808ebe3c05966ab3f18ec2d90d66656a7e8
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5440836
> Reviewed-by: Nico Weber <thakis@chromium.org>
> Reviewed-by: Geoff Lang <geofflang@chromium.org>
> Commit-Queue: Daniel Cheng <dcheng@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1292182}

Bug: 1369167
Change-Id: I9a6217ca54bb447736e41231b198c10c2c4b08ad
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5487297
Commit-Queue: Mikihito Matsuura <mikt@google.com>
Auto-Submit: Mikihito Matsuura <mikt@google.com>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Owners-Override: Mikihito Matsuura <mikt@google.com>
Cr-Commit-Position: refs/heads/main@{#1292285}
NOKEYCHECK=True
GitOrigin-RevId: a5fa896c018d86f5651cea407d0705409e4371b2